services:
  - type: web
    name: stockroom-lavalust
    runtime: docker
    plan: free
    healthCheckPath: /health.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_DRIVER
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL_REQUIRED
        value: "true"
      - key: DB_SSL_CA
        value: /var/www/html/certs/ca.pem
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
