<?php $title = 'Products'; require APP_DIR . 'views/products/header.php';
$totalQuantity = array_sum(array_column($products, 'quantity'));
$lowStock = count(array_filter($products, static fn($p) => $p['quantity'] > 0 && $p['quantity'] <= 5));
?>
<div class="page-heading"><div><p class="eyebrow">YOUR WORKSPACE</p><h1>Products</h1><p class="muted">A clear view of everything on your shelves.</p></div><a class="button primary" href="<?= site_url('products/create') ?>"><span aria-hidden="true">+</span> Add product</a></div>
<?php if ($notice): ?><div class="alert success" role="status"><?= product_escape($notice) ?></div><?php endif; ?>
<div class="stats"><article class="card stat"><span>Total products</span><strong><?= count($products) ?></strong><small>In your catalog</small></article><article class="card stat"><span>Units in stock</span><strong><?= number_format($totalQuantity) ?></strong><small>Across all products</small></article><article class="card stat"><span>Low stock</span><strong><?= $lowStock ?></strong><small>Products with 1–5 units</small></article></div>
<section class="card catalog"><div class="table-heading"><h2>Product catalog</h2><span class="muted"><?= count($products) ?> products</span></div>
<?php if (!$products): ?><div class="empty"><span class="empty-icon" aria-hidden="true">&#9638;</span><h2>Your shelves are ready</h2><p class="muted">Add your first product to start building your inventory.</p><a class="button primary" href="<?= site_url('products/create') ?>">Add your first product</a></div>
<?php else: ?><div class="table-scroll"><table><thead><tr><th>Product</th><th>Price</th><th>Quantity</th><th>Status</th><th>Created</th><th class="right">Actions</th></tr></thead><tbody>
<?php foreach ($products as $product): ?><tr><td><strong><?= product_escape($product['product_name']) ?></strong><p class="description"><?= product_escape($product['description']) ?></p><small class="muted">#<?= (int) $product['id'] ?></small></td><td class="nowrap">&#8369;<?= number_format((float) $product['price'], 2) ?></td><td><?= number_format((int) $product['quantity']) ?></td><td><span class="badge <?= $product['quantity'] == 0 ? 'out' : ($product['quantity'] <= 5 ? 'low' : '') ?>"><?= $product['quantity'] == 0 ? 'Out of stock' : ($product['quantity'] <= 5 ? 'Low stock' : 'In stock') ?></span></td><td class="nowrap muted"><?= product_escape(substr($product['created_at'], 0, 10)) ?></td><td class="right nowrap"><a class="text-link" href="<?= site_url('products/edit/' . (int) $product['id']) ?>" aria-label="Edit <?= product_escape($product['product_name']) ?>">Edit</a><a class="text-link danger-text" href="<?= site_url('products/delete/' . (int) $product['id']) ?>" aria-label="Delete <?= product_escape($product['product_name']) ?>">Delete</a></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></section>
<?php require APP_DIR . 'views/products/footer.php'; ?>
